### PR TITLE
Update Pkgfile

### PR DESCRIPTION
**Pull request by xeneloid**
Added Russian and German language for kde

### CODE REVIEW

**Comment by Pierre-NuTyX** [comment]
Pourquoi doubler de ?

-for lang in da **de** es fi fr it nb nl pt sv
 +for lang in da **de** es fi fr it nb nl pt sv ru **de**

**Comment by tnut** [comment]
il a pas vu qu il y etait deja

**Comment by Pierre-NuTyX** [comment]
je me doute. c'était juste pour dire de faire attention. 
la c'est facile, mais dès fois c'est plus vicieux :-D

**Comment by xeneloid** [comment]
Sorry,I can't talk on french
29 Июн 2016 г. 10:58 пользователь "Pierre-NuTyX" <notifications@github.com>
написал:

**Comment by tnut** [comment]
No prob xeneloid we can fix the kde package. What about the installer I dont think glibc provide russian characters If I had Russia Moscou in english is that ok ?

**Comment by xeneloid** [comment]
Please add russian

1 июля 2016 г. 14:12 пользователь "tnut" <notifications@github.com> написал:

**Comment by tnut** [comment]
NuTyX Version 8.2 will have Russian locales included. If you like to try the 8.2 beta4, please feel free

**Pull request merged**
